config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'
  get 'products/new'
  devise_for :users
  root 'homes#index'
  resources :carts do
  	get :checkout, on: :collection
  end
  resources :cart_items
  resources :two_wheelers do
  	get :get_two_wheeler, on: :collection
  end
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :two_wheeler
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :two_wheeler
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/two_wheeler.rb
class TwoWheeler < ApplicationRecord
	has_one :cart
	has_many :cart_items
	has_many :photos
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # before_action :cart_items_count
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_cart(user)
		if user.cart.present?
			cart = user.cart
		else
			cart = user.create_cart
		end
		cart
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def cart_items_count
    @item_counts = current_user.cart.cart_items.count
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
	def index
		@cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    @photos = @cart_items
	end

  def checkout

  end

  def create
  	if current_user.present?
  		@cart = current_cart(current_user)
  		if @cart.cart_items.find_by_two_wheeler_id(params[:bike_dashboard_id]).blank?
  			@cart_items = @cart.cart_items.new(two_wheeler_id: params[:bike_dashboard_id])
  			if @cart_items.save
  				@message = "Item Added Successfully"
  			end
  		else
  			@message = "Item already present"
  		end
  		respond_to do |format|
  			format.js{}
  		end
  	else
  		redirect_to :user_sign_in_path, flash[:notice] = 'Please login first'
  	end
    @purchased_products = current_user.try(:cart).try(:cart_items) || []
  end

  def destroy
  @cartitem = CartItem.find(params[:id])
    if @cartitem.destroy
      flash[:notice] = "Product deleted"
      redirect_to carts_path
    else
      flash[:alert] = "Error deleting product!"
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  	@two_wheelers = TwoWheeler.all
  	@cart = current_user.cart
  	@cart_items = CartItem.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  	@photos = Photo.all
  end

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
  	if @photo.save
  		reditect_to carts_path
  	else
  		render :new
  	end
  end

  def photo_params
  	params.require(:photo).permit(:image)
  end
end

app/controllers/two_wheelers_controller.rb
class TwoWheelersController < ApplicationController
  def index
    @two_wheelers = TwoWheeler.all
  end

  def new
    @two_wheeler = TwoWheeler.new
  end

  def create
    @two_wheeler = TwoWheeler.new(two_wheeler_params)
    if @two_wheeler.save
      redirect_to root_path, notice: "two_wheeler added successfully"
    else
      render :new
    end
  end
  
  def destroy
    @two_wheeler = TwoWheeler.find(params[:id])
    if @two_wheeler.destroy
      redirect_to root_path
    else
      flash[:alert] = "Error deleting product!"
    end
  end
    
  def get_two_wheeler
    @two_wheeler = TwoWheeler.find(params[:two_wheeler_id])
    respond_to do |format|
      format.js{}
    end
  end

  private

  def two_wheeler_params
    params.require(:two_wheeler).permit(:title, :description, :specification, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bike_dashboard_img(bike)
		if bike.image.present?
	    image_tag bike.image.url
	  else
	    image_tag 'default_bike.png'
	  end
	end

	def product_dashboard_img(product)
		if product.image.present?
	    image_tag product.image.url
	  else
	    image_tag 'default_bike.png'
	  end
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/two_wheelers_helper.rb
module TwoWheelersHelper
end

app/views/carts/checkout.html.erb
SIDDHESH DALVI

<!DOCTYPE html>
<html lang="en">
	<body>
		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#">Hot Deals</a></li>
						<li><a href="#">Categories</a></li>
						<li><a href="#">Laptops</a></li>
						<li><a href="#">Smartphones</a></li>
						<li><a href="#">Cameras</a></li>
						<li><a href="#">Accessories</a></li>
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Checkout</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Checkout</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">Billing address</h3>
							</div>
							<div class="form-group">
								<input class="input" type="text" name="first-name" placeholder="First Name">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="last-name" placeholder="Last Name">
							</div>
							<div class="form-group">
								<input class="input" type="email" name="email" placeholder="Email">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="address" placeholder="Address">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="city" placeholder="City">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="country" placeholder="Country">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
							</div>
							<div class="form-group">
								<input class="input" type="tel" name="tel" placeholder="Telephone">
							</div>
							<div class="form-group">
								<div class="input-checkbox">
									<input type="checkbox" id="create-account">
									<label for="create-account">
										<span></span>
										Create Account?
									</label>
									<div class="caption">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
										<input class="input" type="password" name="password" placeholder="Enter Your Password">
									</div>
								</div>
							</div>
						</div>
						<!-- /Billing Details -->

						<!-- Shiping Details -->
						<div class="shiping-details">
							<div class="section-title">
								<h3 class="title">Shiping address</h3>
							</div>
							<div class="input-checkbox">
								<input type="checkbox" id="shiping-address">
								<label for="shiping-address">
									<span></span>
									Ship to a diffrent address?
								</label>
								<div class="caption">
									<div class="form-group">
										<input class="input" type="text" name="first-name" placeholder="First Name">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="last-name" placeholder="Last Name">
									</div>
									<div class="form-group">
										<input class="input" type="email" name="email" placeholder="Email">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="address" placeholder="Address">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="city" placeholder="City">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="country" placeholder="Country">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
									</div>
									<div class="form-group">
										<input class="input" type="tel" name="tel" placeholder="Telephone">
									</div>
								</div>
							</div>
						</div>
						<!-- /Shiping Details -->

						<!-- Order notes -->
						<div class="order-notes">
							<textarea class="input" placeholder="Order Notes"></textarea>
						</div>
						<!-- /Order notes -->
					</div>

					<!-- Order Details -->
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Your Order</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">
								<div><strong>PRODUCT</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
								<div class="order-col">
									<div>1x Product Name Goes Here</div>
									<div>$980.00</div>
								</div>
								<div class="order-col">
									<div>2x Product Name Goes Here</div>
									<div>$980.00</div>
								</div>
							</div>
							<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
								<div><strong class="order-total">$2940.00</strong></div>
							</div>
						</div>
						<div class="payment-method">
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-1">
								<label for="payment-1">
									<span></span>
									Direct Bank Transfer
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-2">
								<label for="payment-2">
									<span></span>
									Cheque Payment
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-3">
								<label for="payment-3">
									<span></span>
									Paypal System
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
						</div>
						<div class="input-checkbox">
							<input type="checkbox" id="terms">
							<label for="terms">
								<span></span>
								I've read and accept the <a href="#">terms & conditions</a>
							</label>
						</div>
						<a href="#" class="primary-btn order-submit">Place order</a>
					</div>
					<!-- /Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->		
	</body>
</html>

app/views/homes/_bike_details_modal_content.html.erb
<% if @two_wheeler.present? %>
  <div class="modal-header">
    <center><h4 class="modal-title"><%= @two_wheeler.title %></h4></center>
  </div>
  <div class="modal-body">
    <div class="desc">
      <strong><center>Description : </center></strong><%= @two_wheeler.description %>
    </div><br/>

    <div class="desc">
      <strong><center>Specification : </center></strong><%= @two_wheeler.specification %>
    </div><br/>

    <div class="desc">
      <strong>Price : ₹</strong><%= @two_wheeler.price %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/homes/_bike_details_pop_up.html.erb
<div class="container">
  <div class="modal fade" id="bikeDetailModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <%= render 'bike_details_modal_content' %>
      </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<body>
		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#">Hot Deals</a></li>
						<li><a href="#">Categories</a></li>
						<li><a href="#">Laptops</a></li>
						<li><a href="#">Smartphones</a></li>
						<li><a href="#">Cameras</a></li>
						<li><a href="#">Accessories</a></li>
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- shop -->
					<% @two_wheelers.each do |bike| %>
					<div class="col-md-4 col-xs-6">
						<div class="shop">
							<div class="shop-img">
								<!-- <img src="/images/shop01.png" alt=""> -->
								<%= bike_dashboard_img(bike) %>
							</div>
							<div class="shop-body">
								<h3><%= bike.title%><br>₹<%= bike.price%></h3>
								<a href="#" id = "bike_id_<%= bike.id %>" class="cta-btn two_wheeler_details" data-toggle="modal" data-target="#bikeDetailModal">Details <i class="fa fa-arrow-circle-right"></i></a><br/>
							<%= link_to 'Remove', two_wheeler_path(bike), class: 'cta-btn', method: :delete, data: {confirm: 'Are you sure?'} %><br/>
							<%= link_to 'Book','javascript:;', id: "bike_#{bike.id}", class: 'bike_listings cta-btn' %>
							</div>
						</div>
					</div>
						<% end %>
					<!-- /shop -->					
		<!-- /SECTION -->
<!-- =================================================add to cart section============================================ -->
		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- section title -->
						<div class="col-md-12">
							<div class="section-title">
								<h3 class="title">New Products</h3>
								<div class="section-nav">
									<ul class="section-tab-nav tab-nav">
										<li class="active"><a data-toggle="tab" href="#tab1">Laptops</a></li>
										<li><a data-toggle="tab" href="#tab1">Smartphones</a></li>
										<li><a data-toggle="tab" href="#tab1">Cameras</a></li>
										<li><a data-toggle="tab" href="#tab1">Accessories</a></li>
									</ul>
								</div>
							</div>
						</div>
						<!-- /section title -->

						<!-- Products tab & slick -->
						<div class="col-md-12">
							<div class="row">
								<div class="products-tabs">
									<!-- tab -->
									<div id="tab1" class="tab-pane active">
										<div class="products-slick" data-nav="#slick-nav-1">
											<!-- product -->
											<%# @products.each do |product| %>
												<div class="product">
													<div class="product-img">
														<%#= product_dashboard_img(product) %>
													</div>
													<div class="product-body">
														<p class="product-category"><%#= product.title %></p>
														<h3 class="product-name"><a href="#"><%#= product.description %></a></h3>
														<h4 class="product-price">₹<%#= product.price %> <del class="product-old-price">₹6852</del></h4>
														<div class="product-rating">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
														</div>
														<div class="product-btns">
															<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
															<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
															<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
														</div>
													</div>
													<div class="add-to-cart">
														<%#= button_to "Remove", product_path(product), method: :delete, data: { confirm: "Are you sure?" }, class: "add-to-cart-btn fa fa-shopping-cart" %>
														<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
													</div>
												</div>
											<%# end %>	
											<!-- /product -->
										</div>
										<div id="slick-nav-1" class="products-slick-nav"></div>
									</div>
									<!-- /tab -->
								</div>

							</div>
						</div>
						<!-- Products tab & slick -->
					</div>
					<!-- /row -->
				</div>
			
			<!-- /container -->
		</div>
		<!-- /SECTION -->
<!-- ====================*******END add to cart section***********============================================ -->
		<!-- HOT DEAL SECTION -->
		<div id="hot-deal" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="hot-deal">
							<ul class="hot-deal-countdown">
								<li>
									<div>
										<h3>02</h3>
										<span>Days</span>
									</div>
								</li>
								<li>
									<div>
										<h3>10</h3>
										<span>Hours</span>
									</div>
								</li>
								<li>
									<div>
										<h3>34</h3>
										<span>Mins</span>
									</div>
								</li>
								<li>
									<div>
										<h3>60</h3>
										<span>Secs</span>
									</div>
								</li>
							</ul>
							<h2 class="text-uppercase">hot deal this week</h2>
							<p>New Collection Up to 50% OFF</p>
							<a class="primary-btn cta-btn" href="#">Shop now</a>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /HOT DEAL SECTION -->		

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->
	</body>
</html>


<%= render 'homes/bike_details_pop_up', two_wheelers: @two_wheelers %>

<script>
	$(document).ready(function(){
		$(".two_wheeler_details").on('click', function(){
			var two_wheeler_id = $(this).attr('id')
			var two_wheeler_id = two_wheeler_id.split("bike_id_")[1]
			$.ajax({
				url: "<%= get_two_wheeler_two_wheelers_path %>",
				type: 'GET',
				data: {
				two_wheeler_id: two_wheeler_id
				}
			});
		});
		$(".bike_listings").on('click',function(){
			var bike_dashboard_id = $(this).attr('id')
			var bike_dashboard_id = bike_dashboard_id.split('bike_')[1]
			$.ajax({
				url: "<%= carts_path %>",
				type: "POST",
				data: {
					bike_dashboard_id: bike_dashboard_id
				}
			});
			// alert(bike_dashboard_id)
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElectroBike</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="/assets/bootstrap.min.css"/>

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="/assets/slick.css"/>
    <link type="text/css" rel="stylesheet" href="/assets/slick-theme.css"/>

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="/assets/nouislider.min.css"/>

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="/assets/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="/assets/style.css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
        <%= render 'shared/header'%>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
        <%= yield %>
    <% if current_user.present? %>
        <%= render 'shared/footer'%>
    <% end %>
  </body>
<script src="/assets/jquery.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/slick.min.js"></script>
<script src="/assets/nouislider.min.js"></script>
<script src="/assets/jquery.zoom.min.js"></script>
<script src="/assets/main.js"></script>
</html>

app/views/photos/index.html.erb
PHOTO#INDEX

app/views/photos/new.html.erb
<%= form_for @photo do |photo| %>
	<div class="form-group">
		<%= photo.label :image %>
		<%= photo.file_field :image, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= photo.submit 'Create' , class: "btn-primary"%>
		</div>
<% end %>

app/views/shared/_header.html.erb
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
				<div id="top-header">
					<div class="container">
						<ul class="header-links pull-left">
							<li><a href="#"><i class="fa fa-user"></i> <%= current_user.name %></a></li>
							<li><a href="#"><i class="fa fa-envelope-o"></i><%= current_user.email %></a></li>
							<li><%= link_to "New Bike",new_two_wheeler_path %></li>
							<li><%= link_to "Upload Photo",new_photo_path %></li>
						</ul>
						<ul class="header-links pull-right">
							<!-- <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li> -->
							<!-- <li><a><i class="fa fa-user-o"></i> My Account</a></li>						 -->
							<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "fa fa-user-o " %></li>
						</ul>
					</div>
				</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<%= link_to root_path,class: "logo" do %>
								  <%= image_tag "/images/logo.png" %>
								<% end %>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form>
									<select class="input-select">
										<option value="0">All Categories</option>
										<option value="1">Category 01</option>
										<option value="1">Category 02</option>
									</select>
									<input class="input" placeholder="Search here">
									<button class="search-btn">Search</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="#">
										<i class="fa fa-heart-o"></i>
										<span>Your Wishlist</span>
										<div class="qty">2</div>
									</a>
								</div>
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										<div class="qty"><%= current_user.cart.cart_items.count %></div>
										<%# binding.pry %>
									</a>
									<div class="cart-dropdown">
										<!-- CART ITEM LIST -->
										<% if @item_counts.present? && @cart.present? %>
										<%# binding.pry %>
											<% @cart.cart_items.each do |ci| %> 
												<div class="cart-list">
													<%# for product in current_user.cart.cart_items  %>
													<div class="product-widget">
														<div class="product-img">

															<!-- <img src="/images/product01.png" alt=""> -->
															<%= bike_dashboard_img(ci.two_wheeler) %>
														</div>
														<div class="product-body">
															<h3 class="product-name"><a href="#"><%= ci.two_wheeler.title %></a></h3>
															<h4 class="product-price"><span class="qty">1x</span>₹<%= ci.two_wheeler.price %></h4>
														</div>
														<!-- <button class="delete"><i class="fa fa-close"></i></button> -->
														<%= button_to 'X', cart_path(ci), class: 'delete', method: :delete, data: {confirm: 'Are you sure?'} %>
													</div>											
												</div>
											<% end %>
										<% end %>

										
										<!-- //////////CART ITEM LIST -->

										<!-- CART TOTAL AMOUNT -->										
										<div class="cart-summary">
											<small>3 Item(s) selected</small>
											<h5>SUBTOTAL: ₹123</h5>
										</div>
										<!-- /CART TOTAL AMOUNT -->

										<div class="cart-btns">
											<!-- <a href="#">View Cart <i class="view-cart"></i></a> -->
											<%= link_to "View Cart", carts_path %>
											<a href="#">Checkout  <i class="fa fa-arrow-circle-right Checkout"></i></a>											
										</div>							
									</div>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->




<!-- POPUP MODEL FOR NEW BIKE -->


<!-- <script>
	$(document).ready(function(){
		$(".checkout").on('click',function(){
			document.location.href = "/carts/checkout"
		});
		$(".view-cart").on('click',function(){
			alert(123);
		});
	});

</script> -->